### ISSUE TITLE
Bug: letsencrypt.sh does not produce valid domain validation key files and domains cannot be validated

### ISSUE THREAD

**Issue by warpedgeoid** [gheift/letsencrypt.sh#11]
letsencrypt.sh does not properly produce validation files that can be used to validate domains. The files contain an extra period that prevents them from being considered valid by Let's Encrypt. I tracked this behavior down to this:

https://github.com/gheift/letsencrypt.sh/commit/a31ae66f74fc092e46e97141f253c840ee79ec9f?diff=split

The change is on line 343.

**Comment by gheift** [comment]
fixed by pulling your commit.
