### ISSUE TITLE
Simple man how to use it? 

### ISSUE THREAD

**Issue by mrPsycho** [gheift/letsencrypt.sh#2]
please! 
it is not very obvious :)

**Comment by gheift** [comment]
I am writing the README file, but its not finished yet. Here is a first introduction:

https://groups.google.com/a/letsencrypt.org/d/msg/client-dev/D7ww5KzdP9w/5h4hML-DDwAJ

**Comment by mrPsycho** [comment]
cool, thanks!

On Wed, Dec 9, 2015 at 1:00 PM, Gerhard Heift notifications@github.com
wrote:

> I am writing the README file, but its not finished yet. Here is a first
> introduction:
> 
> https://groups.google.com/a/letsencrypt.org/d/msg/client-dev/D7ww5KzdP9w/5h4hML-DDwAJ
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gheift/letsencrypt.sh/issues/2#issuecomment-163167976
> .

## 

Yaroslav
