### ISSUE TITLE
shift: can't shift that many

### ISSUE THREAD

**Issue by lepe** [gheift/letsencrypt.sh#22]
It seems that RESP_BODY content changed. 

(Line 310)

> DOMAIN_CHALLENGE="`sed -e '/"http-01"/ ! d; s/.*{\([^}]*"type":"http-01"[^}]*\)}.*/\1/' "$RESP_BODY"`"

But, if you see the content, there is a space: "type":(HERE)"http-01". The same applies to: DOMAIN_TOKEN and DOMAIN_URI

Which makes the regular expression to fail:

```
push response for "type":
./letsencrypt.sh: 374: shift: can't shift that many
```

**Comment by llaumgui** [comment]
Same issue

**Comment by maxdwit** [comment]
correct. same problem.

**Comment by oddtwelve** [comment]
Same here :-( shift: 657: can't shift that many

**Comment by bruncsak** [comment]
Please try my version. I probably fixed this issue. Please give feedback: let us know.

**Comment by maxdwit** [comment]
Tried your version. 
unhandled response while checking verification status of mydomain.com
HTTP/1.1 202 Accepted
I've verified if the displayed "url": is in fact pointing to mydomain.com/.well-known/acme-challenge/xxxxx

**Comment by bruncsak** [comment]
It is fixed now. Could you have an other trial please?

**Comment by maxdwit** [comment]
Works like a charm! Thanks for fixing it brunsak!

**Comment by oddtwelve** [comment]
Thanks, bruncsak. It is working!

**Comment by leaf-node** [comment]
@bruncsak It works for me. :D
